# Dependabot configuration:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    schedule:
      interval: weekly
      day: saturday
      time: 07:00
      timezone: Europe/Berlin
    assignees:
      - NickKaramoff
    labels:
      - dependencies
